# encoding: utf-8
defaults: &defaults
  approval_dept_id:      '4028809b3c6fbaa7013c6fbc39510002'
#  ws_url:                'http://project.zhiyisoft.com:4567/'
  ws_url:                'http://proj.cdu.edu.cn:4567/'
  cas_url:               'http://61.139.87.55:7890/'
  default_count_behave_types: ["请假","旷工","离职","迟到"]
  count_radix:           0.5

  leave_behave_ids:      ["517180761229bcfc56000006","517180761229bcfc56000003","517180761229bcfc56000005","517180761229bcfc56000002","517180761229bcfc56000004"]            #请假
  behave_absent_id:      '517180761229bcfc56000008'  #旷工
  behave_late_id:        '517180761229bcfc5600000a'  #迟到
  behave_away_id:        '517180761229bcfc5600000e'  #离职
  behave_leave_die_id:   '517180761229bcfc56000006'  #丧假
  behave_leave_sick_id:  '517180761229bcfc56000003'  #病假
  behave_leave_marry_id: '517180761229bcfc56000005'  #婚假
  behave_leave_thing_id: '517180761229bcfc56000002'  #事假
  behave_leave_preg_id:  '517180761229bcfc56000004'  #产假
  exel_header: ['所在位置','工号','姓名','请假类型','天数']	




  user_attrs:
    staffid:  'SU_USER_ID'
    nickname_code: 'SU_NICKNAME_CODE'
    nickname_display: 'SU_NICKNAME_DISPLAY'
    phone_num: 'SU_PHONE_NUM'
    username: 'SU_USERNAME'
    user_no: 'SU_USER_NO'
    dept_id: 'SU_DEPT_ID'
    dept_name: 'SD_DEPT_NAME'
    dept_ancestors: 'DEPT_ANCESTORS'
    position: 'POSTS'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
