# encoding: utf-8
defaults: &defaults
  approval_dept_id:      '4028809b3c6fbaa7013c6fbc39510002'
#  ws_url:                'http://project.zhiyisoft.com:4567/'
  ws_url:                'http://proj.cdu.edu.cn:4567/'
  cas_url:               'http://61.139.87.55:7890/'
  count_radix:           0.5
  export_path:           <%= Rails.root + 'public/exels/'%>

  behaves:
    请假: ["事假","病假","产假","婚假","丧假"]
    旷工: ["旷工"]
    迟到: ["迟到"]
    调休: ["调休"]
    离职: ["离职"]
    上班: ["全勤","公出","培训"]

  exel_header: ['所在位置','工号','姓名','请假类型','天数']		
  exel_worksheet_name: '伊诚公司考勤表'
  count_types:
    leave:          # 请假类型
      leave_die:     '丧假'
      leave_sick:    '病假'
      leave_marry:   '婚假'
      leave_thing:   '事假'
      leave_preg:    '产假'
    absent:         # 矿工类型
      absent:        '旷工'
    late:           # 迟到类型 
      late:          '迟到'
    away:           # 离职类型
      away:          '离职'

  user_attrs:
    staffid:  'SU_USER_ID'
    nickname_code: 'SU_NICKNAME_CODE'
    nickname_display: 'SU_NICKNAME_DISPLAY'
    phone_num: 'SU_PHONE_NUM'
    username: 'SU_USERNAME'
    user_no: 'SU_USER_NO'
    dept_id: 'SU_DEPT_ID'
    dept_name: 'SD_DEPT_NAME'
    dept_ancestors: 'DEPT_ANCESTORS'
    position: 'POSTS'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
