# encoding: utf-8
defaults: &defaults
  approval_dept_id: '4028809b3c6fbaa7013c6fbc39510002'
  ws_url: 'http://project.zhiyisoft.com:4567/'
  cas_url: 'http://61.139.87.55:7890/'
  defult_count_behave_types: ["请假","旷工"]

  user_attrs:
    staffid:  'SU_USER_ID'
    nickname_code: 'SU_NICKNAME_CODE'
    nickname_display: 'SU_NICKNAME_DISPLAY'
    phone_num: 'SU_PHONE_NUM'
    username: 'SU_USERNAME'
    user_no: 'SU_USER_NO'
    dept_id: 'SU_DEPT_ID'
    dept_name: 'SD_DEPT_NAME'
    dept_ancestors: 'DEPT_ANCESTORS'
    position: 'POSTS'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
